
import os


ENV = os.environ["ENV"]
AUTH0_DOMAIN=os.environ["AUTH0_DOMAIN"]
API_AUDIENCE=os.environ["API_AUDIENCE"]
AUTH0_NAMESPACE=os.environ["AUTH0_NAMESPACE"]
API_DOMAIN=os.environ["API_DOMAIN"]

GOOGLE_APPLICATION_CREDENTIALS=os.environ["GOOGLE_APPLICATION_CREDENTIALS"]
FIRESTORE_PROJECT_ID=os.environ["FIRESTORE_PROJECT_ID"]

ALGORITHMS = ["RS256"]
    